-- Sample questions for UBT BASE MVP
-- Run after schema.sql

INSERT INTO public.questions (subject, topic, question, options, answer, explanation) VALUES
-- Mathematics
('mathematics', 'Algebra', 'Solve for x: 2x + 5 = 15', '["x = 3", "x = 5", "x = 7", "x = 10"]', 1, 'Subtract 5 from both sides: 2x = 10. Divide by 2: x = 5.'),
('mathematics', 'Algebra', 'What is the value of x² when x = -3?', '["-9", "9", "6", "-6"]', 1, '(-3)² = (-3) × (-3) = 9. Squaring a negative number gives a positive result.'),
('mathematics', 'Geometry', 'What is the area of a rectangle with length 8 and width 5?', '["13", "26", "40", "80"]', 2, 'Area of rectangle = length × width = 8 × 5 = 40.'),
('mathematics', 'Geometry', 'How many degrees are in the sum of angles in a triangle?', '["90", "180", "270", "360"]', 1, 'The sum of interior angles in any triangle is always 180°.'),
('mathematics', 'Arithmetic', 'What is 15% of 200?', '["15", "20", "30", "35"]', 2, '15% of 200 = 0.15 × 200 = 30.'),
('mathematics', 'Arithmetic', 'Simplify: 3/4 + 1/2', '["4/6", "5/4", "1", "7/8"]', 1, '1/2 = 2/4, so 3/4 + 2/4 = 5/4.'),
('mathematics', 'Functions', 'What is the slope of the line y = 3x + 2?', '["2", "3", "5", "1/3"]', 1, 'In y = mx + b form, m is the slope. Here m = 3.'),
('mathematics', 'Functions', 'If f(x) = x² + 1, what is f(3)?', '["6", "7", "9", "10"]', 3, 'f(3) = 3² + 1 = 9 + 1 = 10.'),
('mathematics', 'Statistics', 'What is the median of: 2, 4, 6, 8, 10?', '["4", "5", "6", "8"]', 2, 'The median is the middle value when data is ordered. The middle of 2,4,6,8,10 is 6.'),
('mathematics', 'Statistics', 'What is the mean of: 10, 20, 30?', '["15", "20", "25", "30"]', 1, 'Mean = (10 + 20 + 30) / 3 = 60 / 3 = 20.'),
('mathematics', 'Trigonometry', 'What is sin(90°)?', '["0", "0.5", "1", "√2/2"]', 2, 'sin(90°) = 1. This is a fundamental trigonometric value.'),
('mathematics', 'Trigonometry', 'In a right triangle, cos(θ) equals:', '["opposite/hypotenuse", "adjacent/hypotenuse", "opposite/adjacent", "hypotenuse/adjacent"]', 1, 'cos(θ) = adjacent side / hypotenuse in a right triangle.'),
('mathematics', 'Equations', 'Solve: x² - 9 = 0', '["x = 3 only", "x = -3 only", "x = ±3", "x = 9"]', 2, 'x² = 9, so x = ±√9 = ±3.'),
('mathematics', 'Equations', 'What are the roots of x² - 5x + 6 = 0?', '["1 and 6", "2 and 3", "-2 and -3", "1 and 5"]', 1, 'Factor: (x-2)(x-3) = 0, so x = 2 or x = 3.'),
('mathematics', 'Probability', 'A coin is flipped. What is P(heads)?', '["1/4", "1/3", "1/2", "1"]', 2, 'A fair coin has 2 equally likely outcomes. P(heads) = 1/2.'),
('mathematics', 'Probability', 'A die is rolled. What is P(getting an even number)?', '["1/6", "1/3", "1/2", "2/3"]', 2, 'Even numbers on a die: 2, 4, 6. P = 3/6 = 1/2.'),
('mathematics', 'Logarithms', 'What is log₁₀(100)?', '["1", "2", "10", "100"]', 1, '10² = 100, so log₁₀(100) = 2.'),
('mathematics', 'Logarithms', 'What is ln(e)?', '["0", "1", "e", "2"]', 1, 'ln(e) = 1 by definition of natural logarithm.'),
('mathematics', 'Sequences', 'What is the 5th term of the arithmetic sequence 2, 5, 8, 11, ...?', '["14", "15", "16", "17"]', 0, 'Common difference d = 3. a₅ = 2 + 4(3) = 14.'),
('mathematics', 'Sequences', 'What is the next term: 1, 2, 4, 8, ...?', '["10", "12", "16", "32"]', 2, 'This is a geometric sequence with ratio 2. Next term = 8 × 2 = 16.'),
('mathematics', 'Inequalities', 'Which value satisfies x > 3?', '["2", "3", "4", "0"]', 2, 'x must be strictly greater than 3. Only 4 satisfies this.'),
('mathematics', 'Inequalities', 'Solve: 2x - 4 < 6', '["x < 1", "x < 5", "x < 10", "x > 5"]', 1, '2x < 10, so x < 5.'),
('mathematics', 'Percentages', 'A price increased from 80 to 100. What is the percentage increase?', '["20%", "25%", "30%", "80%"]', 1, 'Increase = 20. Percentage = (20/80) × 100 = 25%.'),
('mathematics', 'Percentages', 'If 40% of a number is 24, what is the number?', '["40", "50", "60", "96"]', 2, '0.4x = 24, so x = 24/0.4 = 60.'),

-- Informatics
('informatics', 'Programming Basics', 'Which data type stores whole numbers in most programming languages?', '["float", "string", "integer", "boolean"]', 2, 'Integer (int) data type stores whole numbers without decimal points.'),
('informatics', 'Programming Basics', 'What does CPU stand for?', '["Central Process Unit", "Central Processing Unit", "Computer Process Unit", "Core Processing Unit"]', 1, 'CPU = Central Processing Unit — the main processor of a computer.'),
('informatics', 'Algorithms', 'What is the time complexity of binary search?', '["O(n)", "O(log n)", "O(n²)", "O(1)"]', 1, 'Binary search halves the search space each step, giving O(log n) complexity.'),
('informatics', 'Algorithms', 'Which sorting algorithm has average O(n log n) complexity?', '["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"]', 2, 'Merge Sort consistently achieves O(n log n) in all cases.'),
('informatics', 'Data Structures', 'Which structure follows LIFO (Last In, First Out)?', '["Queue", "Stack", "Array", "Linked List"]', 1, 'Stack follows LIFO — the last element added is the first removed.'),
('informatics', 'Data Structures', 'Which structure follows FIFO (First In, First Out)?', '["Stack", "Queue", "Tree", "Graph"]', 1, 'Queue follows FIFO — the first element added is the first removed.'),
('informatics', 'Binary', 'What is the decimal value of binary 1010?', '["8", "10", "12", "14"]', 1, '1010₂ = 1×8 + 0×4 + 1×2 + 0×1 = 10.'),
('informatics', 'Binary', 'What is 7 in binary?', '["110", "111", "101", "1000"]', 1, '7 = 4 + 2 + 1 = 111₂.'),
('informatics', 'Logic', 'What is the result of TRUE AND FALSE?', '["TRUE", "FALSE", "NULL", "ERROR"]', 1, 'AND returns TRUE only when both operands are TRUE.'),
('informatics', 'Logic', 'What is the result of TRUE OR FALSE?', '["TRUE", "FALSE", "NULL", "ERROR"]', 0, 'OR returns TRUE if at least one operand is TRUE.'),
('informatics', 'Networks', 'What does HTTP stand for?', '["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transmission Process", "Host Transfer Text Protocol"]', 0, 'HTTP = HyperText Transfer Protocol, used for web communication.'),
('informatics', 'Networks', 'Which port does HTTPS typically use?', '["21", "80", "443", "8080"]', 2, 'HTTPS uses port 443 by default (HTTP uses port 80).'),
('informatics', 'Databases', 'Which SQL command retrieves data from a table?', '["INSERT", "UPDATE", "SELECT", "DELETE"]', 2, 'SELECT is used to query and retrieve data from database tables.'),
('informatics', 'Databases', 'What is a PRIMARY KEY?', '["A foreign reference", "A unique identifier for each row", "An index on a column", "A backup key"]', 1, 'PRIMARY KEY uniquely identifies each record in a table.'),
('informatics', 'OOP', 'What is encapsulation in OOP?', '["Inheriting from a parent class", "Hiding internal state and requiring interaction through methods", "Creating multiple instances", "Overloading methods"]', 1, 'Encapsulation bundles data and methods while restricting direct access to internal state.'),
('informatics', 'OOP', 'What is inheritance in OOP?', '["Copying code manually", "A class acquiring properties of another class", "Deleting unused objects", "Encrypting data"]', 1, 'Inheritance allows a child class to inherit attributes and methods from a parent class.'),
('informatics', 'Web', 'What does HTML stand for?', '["HyperText Markup Language", "HighText Machine Language", "HyperTransfer Markup Language", "Home Tool Markup Language"]', 0, 'HTML = HyperText Markup Language, the standard for web pages.'),
('informatics', 'Web', 'Which CSS property changes text color?', '["font-size", "color", "background", "margin"]', 1, 'The color property sets the text color in CSS.'),
('informatics', 'Security', 'What is phishing?', '["A fishing game", "Fraudulent attempt to obtain sensitive information", "A type of virus", "Network scanning"]', 1, 'Phishing is a social engineering attack to steal credentials or sensitive data.'),
('informatics', 'Security', 'What does SSL/TLS provide?', '["Faster downloads", "Encrypted communication", "More storage", "Better graphics"]', 1, 'SSL/TLS encrypts data transmitted between client and server.'),
('informatics', 'Python', 'Which keyword defines a function in Python?', '["func", "def", "function", "fn"]', 1, 'Python uses the def keyword to define functions.'),
('informatics', 'Python', 'What is the output of print(3 // 2)?', '["1.5", "1", "2", "0"]', 1, '// is integer division in Python. 3 // 2 = 1.'),
('informatics', 'Memory', 'What is RAM?', '["Read Access Memory", "Random Access Memory", "Run Application Memory", "Remote Access Module"]', 1, 'RAM = Random Access Memory — volatile memory used for active programs.'),
('informatics', 'Memory', 'Which storage is typically fastest?', '["HDD", "SSD", "CD-ROM", "Tape drive"]', 1, 'SSDs use flash memory and are significantly faster than HDDs.');
